version: '3.1'

services:
  db1:
      image: mysql:latest
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: dev
        MYSQL_USER: user1
        MYSQL_PASSWORD: pass
      ports:
        - "3306:3306"

  db2:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_shadow
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"