import * as yup from 'yup';

import {ERROR_TEXT} from '@/constant';

export const GOAL_MAX_LENGTH = 60;
export const GOAL_MIN_LENGTH = 3;
export const GOAL_MAX_LENGTH_ERROR = ERROR_TEXT.MAX_LENGTH(GOAL_MAX_LENGTH);

export const GOAL_ERROR = {
    GOAL_DESCRIPTION_MAX_LENGTH: GOAL_MAX_LENGTH_ERROR,
    GOAL_NAME_MAX_LENGTH: GOAL_MAX_LENGTH_ERROR,
    GOAL_NAME_MIN_LENGTH: ERROR_TEXT.MIN_LENGTH(GOAL_MIN_LENGTH),
    GOAL_NAME_REQUIRED: ERROR_TEXT.REQUIRED,
};

export const GOAL_FIELDS_SCHEMA = yup.object().shape({
    description: yup.string().max(GOAL_MAX_LENGTH, GOAL_ERROR.GOAL_DESCRIPTION_MAX_LENGTH),
    name: yup
        .string()
        .required(GOAL_ERROR.GOAL_NAME_REQUIRED)
        .min(GOAL_MIN_LENGTH, GOAL_ERROR.GOAL_NAME_MIN_LENGTH)
        .max(GOAL_MAX_LENGTH, GOAL_ERROR.GOAL_NAME_MAX_LENGTH),
});
