#!/bin/sh

# Проверяем, что все файлы TypeScript прошли проверку
npm run check:ts

# Если команда завершилась с ошибкой, прерываем коммит
if [ $? -ne 0 ]; then
 echo "Ошибка проверки TypeScript. Коммит отменён."
 exit 1
fi
