name: github-actions-release
run-name: Pull request release branch.
permissions:
  contents: read
  pages: write
  id-token: write
  # Write permissions for pull-requests are required for using the `comment-summary-in-pr` option, comment out if you aren't using this option
  pull-requests: write
on:
    pull_request:
        branches:
            - 'release/*'
            - 'main'

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Install dependencies
              run: npm install

            - name: check:ts
              run: npm run check:ts
    dependency-review:
      runs-on: ubuntu-latest
      steps:
        - name: 'Checkout repository'
          uses: actions/checkout@v4
        - name: 'Dependency Review'
          uses: actions/dependency-review-action@v4
          # Commonly enabled options, see https://github.com/actions/dependency-review-action#configuration-options for all available options.
          with:
            comment-summary-in-pr: always
          #   fail-on-severity: moderate
          #   deny-licenses: GPL-1.0-or-later, LGPL-2.0-or-later
          #   retry-on-snapshot-warnings: true

    test:
        needs: [lint]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Run Vitest
              run: npm run test
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Build and deploy Storybook
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./storybook-static