name: github-actions-push
run-name: Push branch
permissions:
  contents: read
  pages: write
  id-token: write

on: [push]
jobs:
  check-ts:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [ 20 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: check:ts
        run: npm run check:ts
  unit-test:
    needs: [check-ts]
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [ 20 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest
        run: npm run test
