name: github-actions-release
run-name: Pull request release branch.
permissions:
    contents: read
    pages: write
    id-token: write
    # Write permissions for pull-requests are required for using the `comment-summary-in-pr` option, comment out if you aren't using this option
    pull-requests: write
on:
    pull_request:
        branches:
            - 'release/*'
            - 'main'

jobs:
  check-ts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18, 20 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: check:ts
        run: npm run check:ts
  unit-test:
    needs: [check-ts]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18, 20 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run Vitest
        run: npm run test
        
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6 

  deploy-chromatic:
    needs: [check-ts]
    # Operating System
    runs-on: ubuntu-latest
  # Job steps
    steps:
        - uses: actions/checkout@v4
          with:
              fetch-depth: 0
        - name: Use Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'

        - name: Install dependencies
          run: npm install
        #👇 Adds Chromatic as a step in the workflow
        - uses: chromaui/action@v1
          # Options required for Chromatic's GitHub Action
          with:
              #👇 Chromatic projectToken,
              projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
              token: ${{ secrets.GITHUB_TOKEN }}
